services:
  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: coupon_db
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.2-alpine
    container_name: coupon-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: coupon-datadog-agent
    env_file:
      - .env.local
    environment:
      DD_SITE: us5.datadoghq.com
      DD_ENV: local
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:coupon-datadog-agent"
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./logs:/var/log/coupon-system:ro
      - ./datadog/conf.d/mysql.d/conf.yaml:/etc/datadog-agent/conf.d/mysql.d/conf.yaml:ro
      - ./datadog/conf.d/java.d/conf.yaml:/etc/datadog-agent/conf.d/java.d/conf.yaml:ro

volumes:
  mysql-data:
  redis-data:
